server:
  port: 8904
spring:
  application:
    # \u5236\u5B9A\u6CE8\u518C\u5230 Eureka Server \u4E0A\u7684\u670D\u52A1\u540D\u79F0
    name: custom-clientOne
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8903/eureka/
  instance:
    # \u662F\u5426\u6CE8\u518C IP \u5230 eureka server,\u5982\u679C\u4E0D\u6307\u5B9A\u6216\u8BBE\u4E3A false\uFF0C\u90A3\u5C31\u4F1A\u6CE8\u518C\u5230\u4E3B\u673A\u540D\u4E3A eureka server
    prefer-ip-address: true