server:
  port: 8911

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    #false 表示不向注册中心注册
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护实例，并不需要去检索Eureka服务
    fetch-registry: false
    service-url:
      # 设置eureka Client向eureka Server 注册服务的使用地址
       defaultZone: http://localhost:8911/eureka